// Re-export everything from the professional API client
export {
  QueryGeneratorAPIClient as QueryGeneratorAPI,
  ApiError,
  NetworkError,
  AuthenticationError,
  SectorRequiredError,
} from './api-client'

export type {
  LoginRequest,
  LoginResponse,
  GenerateQueryRequest,
  QueryResult,
  UserProfile,
  SectorMembership,
  Sector,
  Role,
  Catalog,
  CatalogSummary,
  SecurityPolicy,
  UpdatePolicyRequest,
  CreateCatalogRequest,
  ApiResponse,
  PaginatedResponse,
  QueryHistoryItem,
  QueryFeedback,
  SubmitFeedbackRequest,
  Correction,
  CostRow,
  CostSummary,
  SettingItem,
  GenModelInfo,
  EmbedModelInfo,
  ModelRegistryResponse,
  UserCostRow,
} from './api-client'
